### ISSUE TITLE
文章列表展示方式写入model

### ISSUE THREAD

**Issue by dreambt** [dreambt/cms4p#13]
根据show_type自动返回合适的展示效果

**Comment by zimoguo** [comment]
你居然下线，不想活了，还是你有别的想法

------------------ 原始邮件 ------------------
发件人: "Baitao Ji"notifications@github.com;
发送时间: 2013年5月23日(星期四) 晚上11:44
收件人: "dreambt/cms4p"cms4p@noreply.github.com; 

主题: [cms4p] 文章列表展示方式写入model (#13)

根据show_type自动返回合适的展示效果
