### ISSUE TITLE
后台-清空数据

### ISSUE THREAD

**Issue by zimoguo** [dreambt/cms4p#21]
建议两个button的颜色互换，或者设置相同的颜色

**Comment by dreambt** [comment]
这个问题已经修改。

**Comment by zimoguo** [comment]
标题很明确

------------------ 原始邮件 ------------------
发件人: "Baitao Ji"; 
发送时间: 2013年5月24日(星期五) 晚上11:02
收件人: "dreambt/cms4p"; 
抄送: "zimoguo"943665622@qq.com; 
主题: Re: [cms4p] 后台-清空数据 (#21)

这个问题已经修改。
